# Generated by Django 4.0.4 on 2022-04-12 05:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('Artist_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Artist_genre', models.CharField(max_length=100)),
                ('Artist_label', models.CharField(max_length=100)),
                ('Artist_grammys', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)])),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('Rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('Rating_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Rating_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewsite.song')),
                ('Rating_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewsite.user')),
            ],
        ),
    ]
