# Generated by Django 4.0.3 on 2022-04-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewsite', '0002_alter_song_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist_name',
            field=models.CharField(max_length=100),
        ),
    ]
