# Generated by Django 4.0.3 on 2022-04-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewsite', '0004_alter_song_artist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='Artist_genre',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='Artist_grammys',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='Artist_label',
        ),
    ]
