# Generated by Django 4.0.3 on 2022-04-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewsite', '0006_alter_song_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='Rating_artist',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
