# Generated by Django 4.0.3 on 2022-04-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewsite', '0008_alter_rating_rating_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='Rating_username',
            field=models.CharField(max_length=30),
        ),
    ]
